--CREATE EXTENSION dblink;
--3849
--alter SEQUENCE res_partner_id_seq RESTART with 3850
--kderp_budget_category_id_seq 
--Select parent_id,customer,supplier,type,* from res_partner where id in (7,8);Select phone,	email from res_partner
--#Insert Partner with Adress

Insert into res_partner
	(id,
	address_id,
	code,
	name,
	vat_code,
	lang,
	customer ,
	supplier ,
	trade_name ,
	street ,
	street2 ,
	city,
	country_id,
	type,
	phone,
	fax,
	mobile,
	email,
	parent_id,
	is_company,
	active,
	notification_email_send,
	display_name)
Select 
	id,
	address_id,
	ref as code,
	name,
	vat_code,
	lang,
	customer ,
	supplier ,
	trade_name ,
	street ,
	street2 ,
	city,
	country_id,
	type,
	phone,
	fax,
	mobile,
	email,
	parent_id,
	is_company,
	True as active,
	'comment' as notification_email_send,
	name as display_name
from dblink('dbname=KDVN_Data user=openerp password=!@#Admin1120 host=172.16.10.192',
'Select * from for_import_partner') as kbn(id int,
	address_id int,
	ref varchar(64),
	name varchar(128),
	vat_code varchar(32),
	lang varchar(64),
	customer boolean,
	supplier boolean,
	trade_name varchar(25),
	street varchar(128),
	street2 varchar(128),
	city varchar(128),
	country_id int,
	type varchar,
	phone varchar(64),
	fax varchar(64),
	mobile varchar(64),
	email varchar(240),
	parent_id int,
	is_company boolean)
where coalesce(id,0)>0 and id<>1

----######################################
--delete from res_partner where id not in (1,3,4,6)
--Select max(id) from res_partner
--alter SEQUENCE res_partner_id_seq RESTART with 5251
--Insert address

Insert into res_partner
	(
	address_id,
	code,
	name,
	vat_code,
	lang,
	customer ,
	supplier ,
	trade_name ,
	street ,
	street2 ,
	city,
	country_id,
	type,
	phone,
	fax,
	mobile,
	email,
	parent_id,
	is_company,
	active,
	notification_email_send,
	display_name)
Select
	address_id,
	null as code,
	name,
	vat_code,
	lang,
	customer ,
	supplier ,
	trade_name ,
	street ,
	street2 ,
	city,
	country_id,
	type,
	phone,
	fax,
	mobile,
	email,
	parent_id,
	is_company,
	True as active,
	'comment' as notification_email_send,
	name as display_name
from dblink('dbname=KDVN_Data user=openerp password=!@#Admin1120 host=172.16.10.192',
'Select * from for_import_partner') as kbn(id int,
	address_id int,
	ref varchar(64),
	name varchar(128),
	vat_code varchar(32),
	lang varchar(64),
	customer boolean,
	supplier boolean,
	trade_name varchar(25),
	street varchar(128),
	street2 varchar(128),
	city varchar(128),
	country_id int,
	type varchar,
	phone varchar(64),
	fax varchar(64),
	mobile varchar(64),
	email varchar(240),
	parent_id int,
	is_company boolean)
where coalesce(id,0)=0