-- -- ALTER TABLE kderp_advance_payment drop CONSTRAINT kderp_advance_payment_advance_number_error_mask;
-- Select * from kderp_advance_payment kap;
-- Update kderp_advance_payment kap set name=replace(name,'C14-','CH14-') where substring(name from 1 for 4)='C14-';
-- Update kderp_advance_payment kap set name=replace(name,'AD14-','ADH14-') where substring(name from 1 for 5)='AD14-';
