-- Select * from res_users where login ilike '%dang%vinh'
--Select * from res_groups_users_rel  where uid =688
-- Delete from res_groups_users_rel  where  uid =688
--Insert into res_groups_users_rel  (uid,gid) Select 688,gid from res_groups_users_rel  where uid=188